Make BackToTop an explicit export from source-react-components
guardian/source pull request #1516
Opened 2022-09-02 12:03 UTC by i-hardy

## What is the purpose of this change?

This fixes an issue with importing the `BackToTop` component in the dev kitchen `FooterWithContents` component.

## What does this change?

-   Make `BackToTop` an explicit export of `@guardian/source-react-components`
-   Import it directly from the package in `FooterWithContents`

2022-09-02 15:37 UTC, joecowton1 approved these changes

2022-09-02 15:38 UTC, sndrs commented on .changeset/honest-cougars-leave.md
> +'@guardian/source-react-components': patch
i think this should be a minor? it's new functionality effectively

2022-09-02 15:38 UTC, sndrs commented
as it's a new export, could you add a story for it?

2022-09-02 15:39 UTC, sndrs requested changes

2022-09-02 15:39 UTC, sndrs commented on .changeset/honest-cougars-leave.md
> +'@guardian/source-react-components': patch
i think this should be a minor? it's new functionality effectively

2022-09-06 12:34 UTC, i-hardy commented
Hey @sndrs, if you have some time to take a look at this today I'd really appreciate it, this is becoming a blocker.

2022-09-06 12:37 UTC, sndrs approved these changes

2022-09-06 12:37 UTC, sndrs commented
apologies @i-hardy – looks great! thanks for the changes 👍

2022-09-06 12:39 UTC, merged